"""Add bookings, rooms and users tables

Revision ID: 3d678ff716a8
Revises: 6dd77e6f629b
Create Date: 2026-05-30 08:18:22.361727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d678ff716a8'
down_revision: Union[str, Sequence[str], None] = '6dd77e6f629b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
